plugins:
  - uses:
      - plugin: "https://ubiquity-os-command-start-stop-main.ubiquity.workers.dev"
        skipBotEvents: false
  - uses:
      - plugin: "https://ubiquity-os-plugin-demo-main.ubiquity.workers.dev"
  - uses:
      - plugin: "https://ubiquity-os-command-wallet-main.ubiquity.workers.dev"
  - uses:
      - plugin: "ubiquity-os-marketplace/command-ask@main"
        with:
          model: "anthropic/claude-3.5-sonnet"
          openAiBaseUrl: "https://openrouter.ai/api/v1"
  - uses:
      - plugin: "https://ubiquity-os-command-query-user-main.ubiquity.workers.dev"
  - uses:
      - plugin: "https://ubiquity-os-daemon-pricing-main.ubiquity.workers.dev"
        skipBotEvents: false
  - uses:
      - plugin: "ubiquity-os-marketplace/text-conversation-rewards@main"
        skipBotEvents: false
        with:
          incentives:
            collaboratorOnlyPaymentInvocation: false
            contentEvaluator: {}
            userExtractor: {}
            dataPurge: {}
            formattingEvaluator: {}
            permitGeneration: {}
            githubComment: {}
          evmPrivateEncrypted: "wJdXHQWB7gI5ApNNWvZejSp5Zj1IBErDKB6zhd_dMGy53JEul6XrjaXSlxpmbtqnFRVfdGY3YA9yCSvPqp3SOGc-LiIx4_unQMoe10w7zgYOpDDOaQul8g0U0pPn6a8_l50QIO6thQmFAcYKdbEbZJalb6xLLU3EcNVasZivhVeCZnj9"
          erc20RewardToken: "0xC6ed4f520f6A4e4DC27273509239b7F8A68d2068"
          evmNetworkId: 100
  - uses:
      - plugin: "ubiquity-os-marketplace/daemon-disqualifier@main"
  - uses:
      - plugin: "https://ubiquity-os-comment-vector-embeddings-main.ubiquity.workers.dev"
